### ISSUE TITLE
Missing STEAM_COMPAT_CLIENT_INSTALL_PATH variable running Proton 6.3

### ISSUE THREAD

**Issue by zerkerX** [caverym/proton-caller#23]
When I attempt to use proton-caller with proton 6.3, it appears to be unable to find an environment variable 'STEAM_COMPAT_CLIENT_INSTALL_PATH'. Full session is as follows:

```
$ proton-call -r MSFC.exe 

________Proton________
Proton: Upgrading prefix from 5.13-1 to 6.3-3 (/var/local/proton//)
Proton: Removing ShellExecute DDE registry entries.
Proton: Removing stale builtin /var/local/proton//pfx//drive_c/windows/system32/amd_ags_x64.dll
Proton: Removing stale builtin /var/local/proton//pfx//drive_c/windows/syswow64/amd_ags_x64.dll
Traceback (most recent call last):
  File "/usr/local/games/steam/steamapps/common//Proton 6.3/proton", line 1031, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/usr/local/games/steam/steamapps/common//Proton 6.3/proton", line 860, in init_session
    g_compatdata.setup_prefix()
  File "/usr/local/games/steam/steamapps/common//Proton 6.3/proton", line 483, in setup_prefix
    steamdir = os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"]
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'
______________________

error: Proton exited with error
```

Manually forcing version 5.13 works fine. I have also tried with a blank prefix folder, and did not have any additional luck.

Config for reference:
```
data = "/var/local/proton/"
common = "/usr/local/games/steam/steamapps/common/"
```

(And yes, I can write to /var/local/proton)

**Comment by caverym** [comment]
I already know about this error, I will probably be pushing a patch tomorrow to fix this (along with the new error handling and updated configuration). Thank you.
