### ISSUE TITLE
thread 'main' panicked at 'no entry found for key', src/bin/proton-call.rs:63:18

### ISSUE THREAD

**Issue by HadetTheUndying** [caverym/proton-caller#26]
I had it working by manually specifying the proton version but now it seems to not care about that and just eats itself. Here's a backtrace hopefully it's just something i'm doing wrong.

```
20:59:02 hadet@endurance ~ → RUST_BACKTRACE=full proton-call -p 5.13
thread 'main' panicked at 'no entry found for key', src/bin/proton-call.rs:63:18
stack backtrace:
   0:     0x560788031970 - std::backtrace_rs::backtrace::libunwind::trace::h64b1884aa50ffb8a
                               at /builddir/rustc-1.53.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560788031970 - std::backtrace_rs::backtrace::trace_unsynchronized::h5d0ebc42d12719e2
                               at /builddir/rustc-1.53.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560788031970 - std::sys_common::backtrace::_print_fmt::h05d119ae97655abb
                               at /builddir/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560788031970 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h065a832482834301
                               at /builddir/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56078801db1f - core::fmt::write::h2b69bbb8432077e1
                               at /builddir/rustc-1.53.0-src/library/core/src/fmt/mod.rs:1094:17
   5:     0x560788031054 - std::io::Write::write_fmt::h7ba36cb591b30c0e
                               at /builddir/rustc-1.53.0-src/library/std/src/io/mod.rs:1584:15
   6:     0x56078803033e - std::sys_common::backtrace::_print::hb4b1d2690d9a1f3f
                               at /builddir/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56078803033e - std::sys_common::backtrace::print::ha9d51dfefc249f82
                               at /builddir/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56078803033e - std::panicking::default_hook::{{closure}}::h4a86d06b0c355a30
                               at /builddir/rustc-1.53.0-src/library/std/src/panicking.rs:208:50
   9:     0x56078803033e - std::panicking::default_hook::hf15750add1a66ef3
                               at /builddir/rustc-1.53.0-src/library/std/src/panicking.rs:225:9
  10:     0x56078803033e - std::panicking::rust_panic_with_hook::h890451a2e631ad12
                               at /builddir/rustc-1.53.0-src/library/std/src/panicking.rs:591:17
  11:     0x56078804a038 - std::panicking::begin_panic_handler::{{closure}}::h33319620d050e505
                               at /builddir/rustc-1.53.0-src/library/std/src/panicking.rs:497:13
  12:     0x560788049fac - std::sys_common::backtrace::__rust_end_short_backtrace::h41c9a51013c798bc
                               at /builddir/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x560788049f5d - rust_begin_unwind
                               at /builddir/rustc-1.53.0-src/library/std/src/panicking.rs:493:5
  14:     0x5607880116d0 - core::panicking::panic_fmt::h4cabb5e7744685f2
                               at /builddir/rustc-1.53.0-src/library/core/src/panicking.rs:92:14
  15:     0x560788011d02 - core::option::expect_failed::h10a95671cee9fc01
                               at /builddir/rustc-1.53.0-src/library/core/src/option.rs:1241:5
  16:     0x560788013fdb - <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index::hde2fabe5709c0fc8
  17:     0x560788018b4f - proton_call::proton_caller::hbe2f08d5ec973dd8
  18:     0x56078801527a - proton_call::main::hc047eed855343839
  19:     0x560788013fe0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h05fc8b201a1a1c1c
  20:     0x56078801b32a - main
  21:     0x7f1d0504ee0a - __libc_start_main
                               at /builddir/glibc-2.32/csu/../csu/libc-start.c:314:16
  22:     0x560788013efa - _start
                               at /builddir/glibc-2.32/csu/../sysdeps/x86_64/start.S:120
  23:                0x0 - <unknown>
```

**Comment by Etile0** [comment]
Hi, I was having the same problem so I looked through the code in my error message and realized it was trying to read a value in config with the key "steam". 

I added `steam = <same path as common>` to the config and it worked.
Pretty weird tho...

**Comment by caverym** [comment]
I wrote the needed changes in the release notes for the latest version. I also updated the example config
