### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/data_path/pfx.lock'

### ISSUE THREAD

**Issue by jmanabc** [caverym/proton-caller#27]
`Traceback (most recent call last):
  File "/home/jmanabc/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 987, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/jmanabc/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 816, in init_session
    g_compatdata.setup_prefix()
  File "/home/jmanabc/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 419, in setup_prefix
    with self.prefix_lock:
  File "/home/jmanabc/.local/share/Steam/steamapps/common/Proton 6.3/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/jmanabc/.local/share/Steam/steamapps/common/Proton 6.3/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/jmanabc/.local/share/Steam/steamapps/common/Proton 6.3/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jmanbc/proton/env/pfx.lock'
______________________

error: Proton exited with error`

Error occurs on runtime.

**Comment by caverym** [comment]
Are your `.../Proton` and `.../Proton/env` directories created?

**Comment by jmanabc** [comment]
> Are your `.../Proton` and `.../Proton/env` directories created?

They aren't named that specifically, readme said any empty directory. Do they have to be named like that?

**Comment by caverym** [comment]
They don't have to be specifically named that, ad long as they're created and the config file points to them
